// STUBS DEFINED FOR FUTURE IMPLEMENTATION
// THESE NEED NAMES AND, IDEALLY, ICONS!
/area/bridge/secondary
/area/chapel/chapel_morgue
/area/chapel/main
/area/chapel/office
/area/crew_quarters/bar
/area/crew_quarters/barrestroom
/area/crew_quarters/captain
/area/crew_quarters/kitchen
/area/crew_quarters/locker
/area/crew_quarters/medbreak
/area/crew_quarters/medical_restroom
/area/crew_quarters/pool
/area/crew_quarters/recreation_area
/area/crew_quarters/recreation_area_restroom
/area/crew_quarters/sleep/cryo
/area/crew_quarters/sleep/Dorm_1
/area/crew_quarters/sleep/Dorm_2
/area/crew_quarters/sleep/Dorm_3
/area/crew_quarters/sleep/Dorm_4
/area/crew_quarters/sleep/Dorm_5
/area/crew_quarters/sleep/Dorm_6
/area/crew_quarters/sleep/Dorm_7
/area/crew_quarters/sleep/Dorm_8
/area/crew_quarters/sleep/engi_wash
/area/crew_quarters/toilet
/area/crew_quarters/visitor_dining
/area/crew_quarters/visitor_laundry
/area/crew_quarters/visitor_lodging
/area/engineering/atmos/monitoring
/area/engineering/engine_gas
/area/engineering/engine_monitoring
/area/engineering/locker_room
/area/engineering/storage
/area/gateway
/area/hallway/secondary/escape/medical_escape_pod_hallway
/area/holodeck_control
/area/holodeck/alphadeck
/area/hydroponics
/area/hydroponics/cafegarden
/area/janitor
/area/library
/area/maintenance/asmaint2
/area/maintenance/cargo
/area/maintenance/engineering/pumpstation
/area/maintenance/evahallway
/area/maintenance/lower/public_garden_maintenence/upper
/area/maintenance/substation/cargo
/area/maintenance/substation/civilian
/area/maintenance/substation/command
/area/maintenance/substation/engineering
/area/maintenance/substation/medical
/area/maintenance/substation/research
/area/maintenance/substation/security
/area/medical/biostorage
/area/medical/chemistry
/area/medical/medbay_primary_storage
/area/medical/morgue
/area/medical/patient_a
/area/medical/patient_b
/area/medical/patient_c
/area/medical/psych
/area/medical/reception
/area/medical/resleeving
/area/medical/sleeper
/area/medical/surgery
/area/medical/surgery_hallway
/area/medical/virology
/area/medical/virologyaccess
/area/medical/ward
/area/mine/explored/upper_level
/area/outpost/mining_main/airlock
/area/quartermaster/delivery
/area/quartermaster/foyer
/area/quartermaster/office
/area/quartermaster/qm
/area/quartermaster/storage
/area/quartermaster/warehouse
/area/rnd/lockers
/area/rnd/rdoffice
/area/rnd/research_storage
/area/rnd/research/testingrange
/area/rnd/workshop
/area/rnd/xenobiology/xenoflora
/area/rnd/xenobiology/xenoflora_storage
/area/teleporter
/area/teleporter/departing
/area/outpost/mining_main/break_room
/area/outpost/mining_main/dorms
/area/outpost/mining_main/maintenance