/obj/item/book/codex
/obj/item/book/codex/lore/news
/obj/item/book/codex/lore/vir
/obj/item/book/codex/lore/robutt
/obj/item/book/manual/tesla_engine
/obj/item/book/manual/the_humanized_mice
/obj/item/book/custom_library/fiction/blacksmithandkinglybloke
/obj/item/book/custom_library/fiction/irishairmanforseesdeath
/obj/item/book/custom_library/fiction/myrock
/obj/item/book/custom_library/fiction/starsandsometimesfallingones
/obj/item/book/custom_library/fiction/truelovehathmyheart
/obj/item/book/custom_library/nonfiction/freesirisailightbulbs
/obj/item/book/custom_library/reference/fistfulofd6splayersguide
/obj/item/book/custom_library/religious/feastofkubera
/obj/item/book/custom_library/religious/storyoflordganesha
/obj/item/book/custom_library/religious/sungoddessofkorea
/obj/item/book/custom_library/religious/wayofbleedingswan
/obj/item/book/manual/command_guide
/obj/item/book/manual/hydroponics_pod_people
/obj/item/book/manual/medical_cloning
/obj/item/book/manual/research_and_development
/obj/item/book/manual/resleeving
/obj/item/book/manual/security_space_law
/obj/item/book/manual/standard_operating_procedure