/obj/structure/sign/department/ai
/obj/structure/sign/department/bar
/obj/structure/sign/department/biblio
/obj/structure/sign/department/chapel
/obj/structure/sign/department/commander
/obj/structure/sign/department/conference_room
/obj/structure/sign/department/engine
/obj/structure/sign/department/interrogation
/obj/structure/sign/department/medbay
/obj/structure/sign/department/morgue
/obj/structure/sign/department/operational
/obj/structure/sign/department/prison
/obj/structure/sign/department/robo
/obj/structure/sign/department/toxins
/obj/structure/sign/department/virology
/obj/structure/sign/department/xenolab
/obj/structure/sign/directions/elevator
/obj/structure/sign/mining
/obj/structure/sign/nanotrasen