/obj/structure/sign/biohazard
/obj/structure/sign/deathsposal
/obj/structure/sign/deck1
/obj/structure/sign/deck2
/obj/structure/sign/deck3
/obj/structure/sign/department/ai
/obj/structure/sign/department/anomaly
/obj/structure/sign/department/armory
/obj/structure/sign/department/bar
/obj/structure/sign/department/biblio
/obj/structure/sign/department/cargo
/obj/structure/sign/department/chapel
/obj/structure/sign/department/chem
/obj/structure/sign/department/eng
/obj/structure/sign/department/engine
/obj/structure/sign/department/gene
/obj/structure/sign/department/gravi
/obj/structure/sign/department/mail
/obj/structure/sign/department/medbay
/obj/structure/sign/department/morgue
/obj/structure/sign/department/operational
/obj/structure/sign/department/robo
/obj/structure/sign/department/sci
/obj/structure/sign/department/telecoms
/obj/structure/sign/department/toxins
/obj/structure/sign/department/xenolab
/obj/structure/sign/directions/command
/obj/structure/sign/directions/elevator
/obj/structure/sign/directions/supply
/obj/structure/sign/electricshock
/obj/structure/sign/mining
/obj/structure/sign/nanotrasen
/obj/structure/sign/science
/obj/structure/sign/signnew/secure
/obj/structure/sign/xenobio
/obj/structure/sign/atmos_air
/obj/structure/sign/department/bridge
/obj/structure/sign/department/conference_room
/obj/structure/sign/department/virology
/obj/structure/sign/department/prison
/obj/structure/sign/department/interrogation
/obj/structure/sign/department/commander
/obj/structure/sign/department/eva