// MOBS
/mob/living/bot/secbot/slime/slimesky
/mob/living/simple_animal/bird/azure_tit/tweeter
/mob/living/simple_animal/bird/black_bird
/mob/living/simple_animal/fish/bass
/mob/living/simple_animal/fish/koi/poisonous
/mob/living/simple_animal/fish/solarfish
/mob/living/simple_animal/fish/trout
/mob/living/simple_animal/fox/renault
/mob/living/simple_animal/gaslamp
/mob/living/simple_animal/fish/rockfish
/mob/living/simple_animal/hostile/mimic
/mob/living/simple_animal/mouse/white/apple
/mob/living/simple_animal/slime/rainbow/kendrick
/mob/living/simple_animal/sif/fluffy
/mob/living/simple_animal/sif/fluffy/silky
/mob/living/simple_animal/sif/shantak/scruffy
/mob/living/simple_animal/corgi/pug/SirPogsley // TODO: add /dog/ parent type

// OBJECTS
/obj/abstract/landmark/engine_loader
	var/list/list/clean_turfs
/obj/abstract/landmark/free_ai_shell
/obj/abstract/landmark/looking_glass
/obj/abstract/landmark/tram
/obj/effect/blocker
/obj/effect/ceiling
/obj/effect/decal/remains
/obj/effect/map_effect/portal
	var/portal_id
/obj/effect/map_effect/portal/line/side_a
/obj/effect/map_effect/portal/line/side_b
/obj/effect/map_effect/portal/master/side_a
/obj/effect/map_effect/portal/master/side_b
/obj/effect/overmap/visitable/sector/virgo3b
/obj/effect/overmap/visitable/ship/landable/excursion
/obj/effect/overmap/visitable/ship/landable/medivac
/obj/effect/overmap/visitable/ship/landable/securiship
/obj/effect/overmap/visitable/ship/landable/tourbus
/obj/effect/step_trigger/teleporter/planetary_fall/virgo3b
/obj/effect/step_trigger/teleporter/to_mining
/obj/effect/step_trigger/teleporter/to_solars
/obj/effect/step_trigger/teleporter/from_mining
/obj/effect/step_trigger/teleporter/from_solars
/obj/effect/step_trigger/teleporter/to_underdark
/obj/item/ammo_casing/a12g/beanbag
/obj/item/ammo_casing/a12g/pellet
/obj/item/ammo_magazine/clip/c762/practice
/obj/item/ammo_magazine/m45/practice
/obj/item/ammo_magazine/m45/rubber
/obj/item/ammo_magazine/m9mmt/practice
/obj/item/ammo_magazine/s44
/obj/item/antibody_scanner
/obj/item/backup_implanter
/obj/item/scanner/barcode
/obj/item/baton/slime/loaded
/obj/item/bedsheet/bluedouble
/obj/item/bedsheet/browndouble
/obj/item/bedsheet/captaindouble
/obj/item/bedsheet/double
/obj/item/bedsheet/iandouble
/obj/item/bedsheet/mimedouble
/obj/item/bedsheet/orangedouble
/obj/item/bedsheet/reddouble
/obj/item/bedsheet/rddouble
/obj/item/bedsheet/yellowdouble
/obj/item/bone/ribs
/obj/item/bone/skull/unathi
/obj/item/cane/crutch
/obj/item/chems/drinks/bottle/lemonjuice
/obj/item/chems/drinks/metaglass
/obj/item/chems/glass/beaker/cryoxadone
/obj/item/chems/glass/beaker/measuring_cup
/obj/item/chems/glass/bottle/biomass
/obj/item/chems/syringe/antiviral
/obj/item/stock_parts/circuitboard/body_designer
/obj/item/stock_parts/circuitboard/mecha_control
/obj/item/stock_parts/circuitboard/powermonitor
/obj/item/stock_parts/circuitboard/rdconsole
/obj/item/stock_parts/circuitboard/rdserver
/obj/item/stock_parts/circuitboard/resleeving_control
/obj/item/stock_parts/circuitboard/teleporter
/obj/item/stock_parts/circuitboard/transhuman_clonepod
/obj/item/stock_parts/circuitboard/transhuman_resleever
/obj/item/stock_parts/circuitboard/transhuman_synthprinter
/obj/item/clothing/accessory/armor/armguards/bulletproof
/obj/item/clothing/accessory/armor/armguards/laserproof
/obj/item/clothing/accessory/armor/armguards/riot
/obj/item/clothing/accessory/armor/armorplate/ablative
/obj/item/clothing/accessory/armor/armorplate/bulletproof
/obj/item/clothing/accessory/armor/armorplate/riot
/obj/item/clothing/accessory/armor/legguards/bulletproof
/obj/item/clothing/accessory/armor/legguards/laserproof
/obj/item/clothing/accessory/armor/legguards/riot
/obj/item/clothing/accessory/collar/pink
/obj/item/clothing/accessory/collar/shock
/obj/item/clothing/accessory/holster/leg
/obj/item/clothing/accessory/permit/gun
	var/owner
/obj/item/clothing/accessory/permit/gun/bar
/obj/item/clothing/accessory/permit/gun/planetside
/obj/item/clothing/accessory/permit/gun/paramedic
/obj/item/clothing/accessory/poncho/roles/medical
/obj/item/clothing/accessory/scarf/stripedred
/obj/item/clothing/accessory/shiny/gloves
/obj/item/clothing/accessory/shiny/socks
/obj/item/clothing/glasses/gglasses
/obj/item/clothing/glasses/goggles
/obj/item/clothing/glasses/omnihud/all
/obj/item/clothing/glasses/omnihud/rnd
/obj/item/clothing/head/beret/centcom/officer
/obj/item/clothing/head/greenbandana
/obj/item/clothing/head/helmet/space/skrell/black
/obj/item/clothing/head/helmet/space/skrell/white
/obj/item/clothing/head/helmet/space/void/captain
/obj/item/clothing/head/helmet/space/void/exploration
/obj/item/clothing/head/helmet/space/void/medical/emt
/obj/item/clothing/head/helmet/space/void/security/prototype
/obj/item/clothing/head/shiny_hood
/obj/item/clothing/mask/gas/wwii
/obj/item/clothing/mask/smokable/cigarette/joint
/obj/item/clothing/shoes/black
/obj/item/clothing/shoes/boots/jackboots
/obj/item/clothing/shoes/boots/winter/medical
/obj/item/clothing/shoes/magboots/adv
/obj/item/clothing/suit/armor/vest/wolftaur
/obj/item/clothing/suit/fire/firefighter
/obj/item/clothing/suit/space/skrell/black
/obj/item/clothing/suit/space/skrell/white
/obj/item/clothing/suit/space/void/captain
/obj/item/clothing/suit/space/void/exploration
/obj/item/clothing/suit/space/void/medical/emt
/obj/item/clothing/suit/space/void/security/prototype
/obj/item/clothing/under/bathrobe
/obj/item/clothing/under/batter
/obj/item/clothing/under/rank/centcom_officer
/obj/item/clothing/under/rank/medical
/obj/item/clothing/under/shiny/catsuit
/obj/item/cmo_disk_holder
/obj/item/communicator
/obj/item/defib_kit/compact/combat/loaded
/obj/item/defib_kit/compact/loaded
/obj/item/defib_kit/jumper_kit
/obj/item/defib_kit/loaded
/obj/item/fishing_net
/obj/item/fishing_rod/modern/cheap
/obj/item/flame/candle/candelabra
/obj/item/folder/blue_captain
/obj/item/folder/blue_hop
/obj/item/folder/red_hos
/obj/item/folder/white
/obj/item/folder/white_cmo
/obj/item/folder/white_rd
/obj/item/folder/yellow_ce
/obj/item/glasses_kit
/obj/item/gps/command
/obj/item/gps/engineering
/obj/item/gps/security
/obj/item/gun/energy/gun/burst
/obj/item/gun/energy/gun/martin
/obj/item/gun/energy/ionrifle/pistol
/obj/item/gun/energy/netgun
/obj/item/gun/energy/phasegun/pistol
/obj/item/gun/energy/sizegun
/obj/item/gun/energy/stunrevolver
/obj/item/gun/energy/taser/xeno
/obj/item/gun/projectile/automatic/advanced_smg
/obj/item/gun/projectile/automatic/battlerifle
/obj/item/gun/projectile/automatic/bullpup
/obj/item/gun/projectile/automatic/l6_saw
/obj/item/gun/projectile/automatic/p90
/obj/item/gun/projectile/automatic/pdw
/obj/item/gun/projectile/automatic/sts35
/obj/item/gun/projectile/automatic/wt550
/obj/item/gun/projectile/automatic/wt550/lethal
/obj/item/gun/projectile/automatic/z8
/obj/item/gun/projectile/deagle
/obj/item/gun/projectile/heavysniper
/obj/item/gun/projectile/nsfw
/obj/item/gun/projectile/p92x
/obj/item/gun/projectile/revolver/consul
/obj/item/gun/projectile/revolver/detective45
/obj/item/gun/projectile/shotgun/pump/combat
/obj/item/gun/projectile/shotgun/pump/rifle/practice
/obj/item/gun/projectile/shotgun/pump/USDF
/obj/item/handcuffs/fuzzy
/obj/item/handcuffs/legcuffs/fuzzy
/obj/item/mech_component/part/durand_left_leg
/obj/item/module/power_control
/obj/item/multitool/station_buffered
/obj/item/nif/bad
/obj/item/paper/dockingcodes
/obj/item/paper/rogueminer
/obj/item/pen/blade/red
/obj/item/perfect_tele
/obj/item/pizzavoucher
/obj/item/radio/intercom/department/medbay
/obj/item/radio/intercom/department/security
/obj/item/radio/intercom/entertainment
/obj/item/radio/intercom/locked/ai_private
/obj/item/radio/phone/medbay
/obj/item/retail_scanner/civilian
/obj/item/retail_scanner/security
/obj/item/sleevemate
/obj/item/soap/deluxe
/obj/item/soap/nanotrasen
/obj/item/soap/syndie
/obj/item/stack/cable_coil/random_belt
/obj/item/stack/marker_beacon/thirty

/obj/item/storage/bag/circuits/basic
/obj/item/storage/box/backup_kit
/obj/item/storage/box/body_record_disk
/obj/item/storage/box/holowarrants
/obj/item/storage/box/nifsofts_engineering
/obj/item/storage/box/nifsofts_medical
/obj/item/storage/box/nifsofts_mining
/obj/item/storage/box/nifsofts_security
/obj/item/storage/fancy/candle_box
/obj/item/storage/fancy/cigar/havana
/obj/item/storage/fancy/markers
/obj/item/storage/mrebag/pill/sleevingcure
/obj/item/storage/pill_bottle/tramadol
/obj/item/storage/secure/briefcase/ml3m_pack_cmo
/obj/item/storage/secure/briefcase/ml3m_pack_med
/obj/item/tape/random
/obj/item/taperoll/atmos
/obj/item/taperoll/engineering
/obj/item/taperoll/medical
/obj/item/toy/cultsword
/obj/item/toy/eight_ball/conch
/obj/item/toy/katana
/obj/item/toy/nanotrasenballoon
/obj/item/toy/plushie/coffee_fox
/obj/item/toy/plushie/farwa
/obj/item/toy/plushie/mouse/fluff
/obj/item/toy/plushie/purple_fox
/obj/item/toy/plushie/squid/blue
/obj/item/toy/plushie/squid/pink
/obj/item/toy/plushie/therapy/blue
/obj/item/toy/stickhorse
/obj/item/trash/unajerky
/obj/item/tvcamera
/obj/item/twohanded/fireaxe/foam
/obj/item/twohanded/spear/foam
/obj/item/universal_translator
/obj/item/virusdish/random
/obj/machinery/airlock_sensor/airlock_exterior
/obj/machinery/airlock_sensor/airlock_exterior/shuttle
/obj/machinery/airlock_sensor/airlock_interior
/obj/machinery/alarm/freezer
/obj/machinery/appliance/cooker/fryer
/obj/machinery/appliance/cooker/grill
/obj/machinery/appliance/cooker/oven
/obj/machinery/appliance/mixer/candy
/obj/machinery/appliance/mixer/cereal
/obj/machinery/atmospherics/binary/algae_farm/filled
/obj/machinery/atmospherics/binary/pump/fuel
/obj/machinery/atmospherics/pipe/simple/hidden/aux
/obj/machinery/atmospherics/pipe/simple/insulated
/obj/machinery/atmospherics/pipe/vent
/obj/machinery/atmospherics/pipe/vent/high_volume
/obj/machinery/atmospherics/portables_connector/aux
/obj/machinery/atmospherics/portables_connector/fuel
/obj/machinery/atmospherics/tvalve/digital/mirrored
/obj/machinery/atmospherics/unary/cryo_cell
/obj/machinery/atmospherics/unary/vent_pump/high_volume/aux
/obj/machinery/blackbox_recorder
/obj/machinery/bomb_tester
/obj/machinery/button/windowtint/multitint
/obj/machinery/camera/network/cargo
/obj/machinery/camera/network/civilian
/obj/machinery/camera/network/command
/obj/machinery/camera/network/engine
/obj/machinery/camera/network/exploration
/obj/machinery/camera/network/interrogation
/obj/machinery/camera/network/northern_star
/obj/machinery/camera/network/outside
/obj/machinery/camera/network/research_outpost
/obj/machinery/camera/network/research/xenobio
/obj/machinery/camera/network/tether
/obj/machinery/chemical_analyzer
/obj/machinery/chemical_dispenser/biochemistry/full
/obj/machinery/chemical_dispenser/xenoflora/full
/obj/machinery/clonepod/transhuman
/obj/machinery/clonepod/transhuman/full
/obj/machinery/computer/area_atmos/tag
	var/scrub_id
/obj/machinery/computer/centrifuge
/obj/machinery/computer/cryopod/gateway
/obj/machinery/computer/diseasesplicer
/obj/machinery/computer/air_control/large_tank_control
/obj/machinery/computer/id_restorer
/obj/machinery/computer/looking_glass
	var/lg_id = null
/obj/machinery/computer/mecha
/obj/machinery/computer/roguezones
/obj/machinery/computer/shuttle_control/belter
/obj/machinery/computer/shuttle_control/explore/excursion
/obj/machinery/computer/shuttle_control/explore/medivac
/obj/machinery/computer/shuttle_control/explore/securiship
/obj/machinery/computer/shuttle_control/explore/tourbus
/obj/machinery/computer/shuttle_control/surface_mining_outpost
/obj/machinery/computer/shuttle_control/tether_backup
/obj/machinery/computer/timeclock/premade/east
/obj/machinery/computer/timeclock/premade/north
/obj/machinery/computer/timeclock/premade/south
/obj/machinery/computer/timeclock/premade/west
/obj/machinery/computer/transhuman/designer
/obj/machinery/computer/transhuman/resleeving
/obj/machinery/cryopod/robot/door/gateway
/obj/machinery/cryopod/robot/door/tram
/obj/machinery/disease2/diseaseanalyser
/obj/machinery/disease2/incubator
/obj/machinery/disease2/isolator
/obj/machinery/door/airlock/glass/medical/polarized
	var/id_tint
/obj/machinery/door/airlock/glass/security/polarized
	var/id_tint
/obj/machinery/door/airlock/double/glass/polarized
	var/id_tint
/obj/machinery/door/airlock/double/metal
/obj/machinery/door/airlock/double/metal/mait
/obj/machinery/door/airlock/silver
/obj/machinery/door/firedoor/border_only
/obj/machinery/door/firedoor/glass
/obj/machinery/door/firedoor/glass/hidden/steel
/obj/machinery/door/firedoor/multi_tile
/obj/machinery/door/unpowered/shuttle
/obj/machinery/exonet_node
/obj/machinery/fitness/heavy/lifter
/obj/machinery/fitness/punching_bag/clown
/obj/machinery/gear_painter
/obj/machinery/gravity_generator/main/station
/obj/machinery/holoplant
/obj/machinery/holoposter
/obj/machinery/holosign/bar
/obj/machinery/librarycomp
/obj/machinery/librarypubliccomp
/obj/machinery/libraryscanner
/obj/machinery/light/flamp/noshade
/obj/machinery/mineral/equipment_vendor
/obj/machinery/mineral/equipment_vendor/survey
/obj/machinery/mining/drill/loaded
/obj/machinery/network/requests_console/preset/engineering
/obj/machinery/network/requests_console/preset/hos
/obj/machinery/network/requests_console/preset/research
/obj/machinery/ntnet_relay
/obj/machinery/organ_printer/flesh
/obj/machinery/oxygen_pump/anesthetic
/obj/machinery/pda_multicaster/prebuilt
/obj/machinery/porta_turret/ai_defense
/obj/machinery/portable_atmospherics/powered/pump/huge/stationary/purge
/obj/machinery/portable_atmospherics/powered/scrubber/huge/stationary/tram
/obj/machinery/power/grid_checker
/obj/machinery/power/smes/buildable/point_of_interest
/obj/machinery/power/thermoregulator
/obj/machinery/processor
/obj/machinery/scale
/obj/machinery/seed_storage/brig
/obj/machinery/shield_generator/external
/obj/machinery/shuttle_sensor
/obj/machinery/sleep_console
/obj/machinery/smartfridge/chemistry/chemvator/down
/obj/machinery/smartfridge/secure/virology
/obj/machinery/suit_cycler/captain
/obj/machinery/suit_cycler/exploration
/obj/machinery/suit_cycler/prototype
/obj/machinery/transhuman/resleever
/obj/machinery/transhuman/synthprinter
/obj/machinery/vending/blood
/obj/machinery/vending/cola/soft
/obj/machinery/vending/entertainer
/obj/machinery/vending/fishing
/obj/machinery/vending/hydronutrients/brig
/obj/machinery/vending/loadout
/obj/machinery/vending/loadout/accessory
/obj/machinery/vending/loadout/clothing
/obj/machinery/vending/loadout/costume
/obj/machinery/vending/loadout/gadget
/obj/machinery/vending/loadout/loadout_misc
/obj/machinery/vending/loadout/overwear
/obj/machinery/vending/loadout/uniform
/obj/machinery/vending/phoronresearch
/obj/random/carp_plushie
/obj/random/cigarettes
/obj/random/cutout

/obj/random/mob/mouse
/obj/random/mouseremains
/obj/random/slimecore
/obj/random/tetheraid
/obj/random/unidentified_medicine
/obj/structure/barricade/cutout
/obj/structure/barricade/cutout/ntsec
/obj/structure/barricade/cutout/viva
/obj/structure/bed/chair/bay/chair/padded/beige
/obj/structure/bed/chair/bay/chair/padded/blue
/obj/structure/bed/chair/bay/chair/padded/red/bignest
/obj/structure/bed/chair/bay/comfy/blue
/obj/structure/bed/double/padded
/obj/structure/bookcase/manuals/research_and_development
/obj/structure/cable/ender
	var/id_tag
/obj/structure/cable/heavyduty
/obj/structure/closet/autolok_wall
/obj/structure/closet/bombcloset/double
/obj/structure/closet/crate/science
/obj/structure/closet/emcloset/legacy
/obj/structure/closet/emergsuit_wall
/obj/structure/closet/firecloset/full/double
/obj/structure/closet/l3closet/medical
/obj/structure/closet/l3closet/scientist/double
/obj/structure/closet/secure_closet/explorer
/obj/structure/closet/secure_closet/guncabinet/phase
/obj/structure/closet/secure_closet/guncabinet/excursion
/obj/structure/closet/secure_closet/hos2
/obj/structure/closet/secure_closet/hydroponics/sci
/obj/structure/closet/secure_closet/medical_wall/anesthetics
/obj/structure/closet/secure_closet/medical2
/obj/structure/closet/secure_closet/pathfinder
/obj/structure/closet/secure_closet/pilot
/obj/structure/closet/secure_closet/sar
/obj/structure/closet/walllocker_double
/obj/structure/closet/walllocker/emerglocker/north
/obj/structure/closet/walllocker/emerglocker/south
/obj/structure/closet/wardrobe/captain
/obj/structure/closet/wardrobe/detective
/obj/structure/curtain/open/shower/medical
/obj/structure/dancepole
/obj/structure/door_assembly/door_assembly_mai
/obj/structure/door_assembly/multi_tile
/obj/structure/fans/tiny
/obj/structure/flora/skeleton
/obj/structure/flora/tree/jungle
/obj/structure/flora/tree/sif
/obj/structure/ladder/up
/obj/structure/plasticflaps/mining
/obj/structure/rack/shelf/steel
/obj/structure/rack/steel
/obj/structure/reagent_dispensers/coolanttank
/obj/structure/reagent_dispensers/foam
/obj/structure/reagent_dispensers/virusfood
/obj/structure/reagent_dispensers/water_cooler/full
/obj/structure/table/borosilicate
/obj/structure/table/fancyblack
/obj/item/gun/energy/frontier/locked
/obj/item/gun/energy/frontier/locked/holdout

/obj/structure/hygiene/urinal
/obj/item/bedsheet/purpledouble
/obj/machinery/computer/HolodeckControl/holodorm
/obj/machinery/computer/HolodeckControl/holodorm/one
/obj/machinery/computer/HolodeckControl/holodorm/three
/obj/machinery/computer/HolodeckControl/holodorm/five
/obj/machinery/computer/HolodeckControl/holodorm/seven
/obj/machinery/computer/HolodeckControl/holosurgery
/obj/item/scanner/health/advanced
/obj/item/scanner/health/improved
/obj/item/roller/adv

/obj/item/ammo_casing/nsfw_batt
/obj/item/ammo_casing/nsfw_batt/net
/obj/item/ammo_casing/nsfw_batt/stun
/obj/item/ammo_magazine/m44
/obj/item/ammo_magazine/m545
/obj/item/ammo_magazine/m545/ap
/obj/item/ammo_magazine/m545saw
/obj/item/ammo_magazine/m545saw/ap
/obj/item/ammo_magazine/m762
/obj/item/ammo_magazine/m762/ap
/obj/item/ammo_magazine/m95
/obj/item/ammo_magazine/m9mm/large/preban
/obj/item/ammo_magazine/m9mml
/obj/item/ammo_magazine/m9mml/ap
/obj/item/ammo_magazine/m9mmp90
/obj/item/ammo_magazine/m9mmR/saber
/obj/item/ammo_magazine/m9mmt/rubber
/obj/item/ammo_magazine/nsfw_mag
/obj/item/ammo_magazine/s4

/obj/structure/flora/tree/jungle_small

// COOKING
/obj/item/chems/condiment/spacespice
/obj/structure/reagent_dispensers/cookingoil
/obj/machinery/appliance/grill
/obj/item/storage/box/wings
/obj/item/chems/food/roastbeef
/obj/item/chems/food/kitsuneudon
/obj/item/chems/food/lasagna

// RADIO
/obj/item/radio/intercom/locked/confessional
	name = "confessional intercom"
	locked_frequency = 1480

// TELESCI
/obj/machinery/computer/telescience
/obj/item/stock_parts/circuitboard/telesci_pad

// NOTE: SOME OF THESE THINGS MIGHT ALREADY EXIST AND JUST NEED REPATHING!
/obj/item/ammo_magazine/s45
/obj/item/chems/glass/bottle/tramadol
/obj/item/closet_painter
/obj/item/clothing/glasses/sunglasses/sechud/tactical
/obj/item/clothing/gloves/swat
/obj/item/clothing/head/beret/nanotrasen
/obj/item/clothing/head/helmet/bulletproof
/obj/item/clothing/head/helmet/combat
/obj/item/clothing/head/helmet/ert/command
/obj/item/clothing/head/helmet/laserproof
/obj/item/clothing/head/helmet/space/deathsquad
/obj/item/clothing/head/helmet/space/void/headofsecurity
/obj/item/clothing/head/helmet/space/void/medical/bio
/obj/item/clothing/head/pilot
/obj/item/clothing/shoes/mime
/obj/item/clothing/suit/armor/combat
/obj/item/clothing/suit/armor/riot/alt
/obj/item/clothing/suit/armor/swat
/obj/item/clothing/suit/armor/tactical
/obj/item/clothing/suit/armor/vest/ert/command
/obj/item/clothing/suit/space/void/headofsecurity
/obj/item/clothing/suit/space/void/medical/bio
/obj/item/clothing/under/fluff/latexmaid
/obj/item/flame/candle/candelabra/everburn
/obj/item/flame/lighter/zippo/gonzo
/obj/item/gps/internal/base
/obj/item/gunbox
/obj/item/knife/tacknife/survival
/obj/item/modular_computer/pda/captain
/obj/item/ore/bluespace_crystal/artificial
/obj/item/rig_module/rescue_pharm
/obj/item/rig/breacher
/obj/item/storage/bag/chemistry
/obj/item/storage/belt/security/tactical
/obj/item/storage/box/firingpins
/obj/item/storage/pill_bottle/iron
/obj/item/storage/pill_bottle/nutriment
/obj/item/storage/secure/briefcase/nsfw_pack
/obj/item/t_scanner/advanced
/obj/item/toy/plushie/marble_fox
/obj/item/toy/plushie/teshari
/obj/item/toy/plushie/therapy/orange
/obj/machinery/atmospherics/unary/vent_pump/high_volume/wall_mounted
/obj/machinery/button/remote/emitter
/obj/machinery/camera/motion/security
/obj/machinery/camera/network/thunder
/obj/machinery/cash_register/civilian
/obj/machinery/computer/cryopod/dorms
/obj/machinery/computer/shuttle_control/web/excursion
/obj/machinery/door/airlock/voidcraft
/obj/machinery/door/airlock/voidcraft/vertical
/obj/machinery/light/flicker
/obj/machinery/navbeacon/delivery/south
/obj/machinery/particle_smasher
/obj/machinery/shield_capacitor
/obj/machinery/smartfridge/chemistry/virology
/obj/machinery/suit_cycler/director
/obj/machinery/vending/giftvendor
/obj/structure/closet/crate/secure/science
/obj/structure/closet/secure_closet/medical_wall/synth_anesthetics
/obj/structure/closet/secure_closet/nanotrasen_commander
/obj/structure/closet/secure_closet/nanotrasen_security
/obj/structure/closet/secure_closet/nanotrasen_warden
/obj/structure/closet/wardrobe/ert
/obj/structure/fence
/obj/structure/fence/door
/obj/structure/fence/post
/obj/structure/flight_left
/obj/structure/flight_right
/obj/structure/flora/sif/eyes
/obj/structure/flora/sif/tendrils
/obj/structure/musician/piano