/turf/simulated/floor/plating/eris/under
/turf/simulated/floor/tiled/eris/cafe
/turf/simulated/floor/tiled/eris/dark/bluecorner
/turf/simulated/floor/tiled/eris/dark/danger
/turf/simulated/floor/tiled/eris/dark/golden
/turf/simulated/floor/tiled/eris/dark/gray_perforated
/turf/simulated/floor/tiled/eris/dark/techfloor
/turf/simulated/floor/tiled/eris/dark/violetcorener
/turf/simulated/floor/tiled/eris/steel/bar_dance
/turf/simulated/floor/tiled/eris/steel/bar_light
/turf/simulated/floor/tiled/eris/steel/cyancorner
/turf/simulated/floor/tiled/eris/steel/danger
/turf/simulated/floor/tiled/eris/steel/gray_perforated
/turf/simulated/floor/tiled/eris/steel/techfloor_grid
/turf/simulated/floor/tiled/eris/techmaint
/turf/simulated/floor/tiled/eris/techmaint_cargo
/turf/simulated/floor/tiled/eris/techmaint_panels
/turf/simulated/floor/tiled/eris/techmaint_perforated
/turf/simulated/floor/tiled/eris/white/bluecorner
/turf/simulated/floor/tiled/eris/white/orangecorner