// STUBS DEFINED FOR FUTURE IMPLEMENTATION
// THESE NEED NAMES AND, IDEALLY, ICONS!
/area/ai
/area/ai_core_foyer
/area/ai_cyborg_station
/area/ai_monitored/storage/eva
/area/ai_server_room
/area/ai_upload
/area/ai_upload_foyer
/area/bridge_hallway
/area/bridge/meeting_room
/area/bridge/meeting_room/station
/area/bridge/secondary
/area/bridge/secondary/hallway
/area/bridge/secondary/teleporter
/area/chapel/chapel_morgue
/area/chapel/main
/area/chapel/office
/area/crew_quarters/bar
/area/crew_quarters/barrestroom
/area/crew_quarters/captain
/area/crew_quarters/freezer
/area/crew_quarters/heads/chief
/area/crew_quarters/heads/hop
/area/crew_quarters/kitchen
/area/crew_quarters/locker
/area/crew_quarters/locker/laundry_arrival
/area/crew_quarters/medbreak
/area/crew_quarters/medical_restroom
/area/crew_quarters/panic_shelter
/area/crew_quarters/pool
/area/crew_quarters/recreation_area
/area/crew_quarters/recreation_area_restroom
/area/crew_quarters/showers
/area/crew_quarters/sleep/cryo
/area/crew_quarters/sleep/Dorm_1
/area/crew_quarters/sleep/Dorm_1/holo
/area/crew_quarters/sleep/Dorm_2
/area/crew_quarters/sleep/Dorm_3
/area/crew_quarters/sleep/Dorm_3/holo
/area/crew_quarters/sleep/Dorm_4
/area/crew_quarters/sleep/Dorm_5
/area/crew_quarters/sleep/Dorm_5/holo
/area/crew_quarters/sleep/Dorm_6
/area/crew_quarters/sleep/Dorm_7
/area/crew_quarters/sleep/Dorm_7/holo
/area/crew_quarters/sleep/Dorm_8
/area/crew_quarters/sleep/engi_wash
/area/crew_quarters/sleep/maintDorm1
/area/crew_quarters/sleep/maintDorm2
/area/crew_quarters/sleep/maintDorm3
/area/crew_quarters/sleep/spacedorm1
/area/crew_quarters/sleep/spacedorm2
/area/crew_quarters/sleep/spacedorm3
/area/crew_quarters/sleep/spacedorm4
/area/crew_quarters/toilet
/area/crew_quarters/visitor_dining
/area/crew_quarters/visitor_laundry
/area/crew_quarters/visitor_lodging
/area/engineering/atmos
/area/engineering/atmos_intake
	area_flags = AREA_FLAG_EXTERNAL | AREA_FLAG_IS_NOT_PERSISTENT | AREA_FLAG_IS_BACKGROUND | AREA_FLAG_HIDE_FROM_HOLOMAP
	is_outside = TRUE
/area/engineering/atmos/backup
/area/engineering/atmos/gas_storage
/area/engineering/atmos/monitoring
/area/engineering/atmos/processing
/area/engineering/atmos/storage
/area/engineering/break_room
/area/engineering/drone_fabrication
/area/engineering/engine_airlock
/area/engineering/engine_eva
/area/engineering/engine_gas
/area/engineering/engine_monitoring
/area/engineering/engine_room
/area/engineering/engine_smes
/area/engineering/engineering_airlock
/area/engineering/engineering_monitoring
/area/engineering/foyer
/area/engineering/foyer_mezzenine
/area/engineering/gravity_gen
/area/engineering/gravity_lobby
/area/engineering/hallway
/area/engineering/locker_room
/area/engineering/lower/atmos_eva
/area/engineering/lower/atmos_lockers
/area/engineering/lower/breakroom
/area/engineering/lower/lobby
/area/engineering/shaft
/area/engineering/storage
/area/engineering/workshop
/area/gateway
/area/gateway/prep_room
/area/hallway/lower/first_west
/area/hallway/lower/third_south
/area/hallway/secondary/escape/medical_escape_pod_hallway
/area/hallway/station/atrium
/area/hallway/station/docks
/area/hallway/station/port
/area/hallway/station/starboard
/area/hallway/station/upper
/area/holodeck_control
/area/holodeck/alphadeck
/area/hydroponics
/area/hydroponics/cafegarden
/area/janitor
/area/library
/area/looking_glass/lg_1
/area/maintenance/abandonedlibrary
/area/maintenance/abandonedlibraryconference
/area/maintenance/asmaint2
/area/maintenance/cargo
/area/maintenance/commandmaint
/area/maintenance/engineering/pumpstation
/area/maintenance/evahallway
/area/maintenance/lower/atmos
/area/maintenance/lower/bar
/area/maintenance/lower/medsec_maintenance
/area/maintenance/lower/mining
/area/maintenance/lower/mining_eva
/area/maintenance/lower/north
/area/maintenance/lower/public_garden_maintenence
/area/maintenance/lower/public_garden_maintenence/upper
/area/maintenance/lower/research
/area/maintenance/lower/rnd
/area/maintenance/lower/solars
/area/maintenance/lower/south
/area/maintenance/lower/trash_pit
/area/maintenance/lower/vacant_site
/area/maintenance/lower/xenoflora
/area/maintenance/lowmedbaymaint
/area/maintenance/readingrooms
/area/maintenance/station/abandonedholodeck
/area/maintenance/station/ai
/area/maintenance/station/cargo
/area/maintenance/station/elevator
/area/maintenance/station/eng_lower
/area/maintenance/station/eng_upper
/area/maintenance/station/exploration
/area/maintenance/station/medbay
/area/maintenance/station/micro
/area/maintenance/station/sec_lower
/area/maintenance/station/sec_upper
/area/maintenance/station/spacecommandmaint
/area/maintenance/substation/bar
/area/maintenance/substation/cargo
/area/maintenance/substation/civ_west
/area/maintenance/substation/civilian
/area/maintenance/substation/command
/area/maintenance/substation/engineering
/area/maintenance/substation/exploration
/area/maintenance/substation/medical
/area/maintenance/substation/medsec
/area/maintenance/substation/research
/area/maintenance/substation/security
/area/maintenance/substation/spacecommand
/area/maintenance/substation/surface_atmos
/area/maintenance/substation/SurfMedsubstation
/area/maintenance/substation/tcomms
/area/maintenance/tether_midpoint
/area/medical/biostorage
/area/medical/chemistry
/area/medical/exam_room
/area/medical/medbay_primary_storage
/area/medical/morgue
/area/medical/patient_a
/area/medical/patient_b
/area/medical/patient_c
/area/medical/psych
/area/medical/reception
/area/medical/recoveryrestroom
/area/medical/resleeving
/area/medical/sleeper
/area/medical/surgery
/area/medical/surgery_hallway
/area/medical/virology
/area/medical/virologyaccess
/area/medical/virologyisolation
/area/medical/ward
/area/mine/explored/upper_level
/area/outpost/mining_main/airlock
/area/outpost/mining_main/hangar
/area/quartermaster/belterdock
/area/quartermaster/belterdock/gear
/area/quartermaster/belterdock/refinery
/area/quartermaster/belterdock/surface_mining_outpost_shuttle_hangar
/area/quartermaster/delivery
/area/quartermaster/foyer
/area/quartermaster/office
/area/quartermaster/qm
/area/quartermaster/storage
/area/quartermaster/warehouse
/area/rnd/breakroom
/area/rnd/breakroom/bathroom
/area/rnd/chemistry_lab
/area/rnd/external
	area_flags = AREA_FLAG_EXTERNAL | AREA_FLAG_IS_NOT_PERSISTENT | AREA_FLAG_IS_BACKGROUND | AREA_FLAG_HIDE_FROM_HOLOMAP
	is_outside = TRUE
/area/rnd/hallway
/area/rnd/hardstorage
/area/rnd/lockers
/area/rnd/miscellaneous_lab
/area/rnd/outpost/xenobiology/outpost_autopsy
/area/rnd/outpost/xenobiology/outpost_breakroom
/area/rnd/outpost/xenobiology/outpost_decon
/area/rnd/outpost/xenobiology/outpost_first_aid
/area/rnd/outpost/xenobiology/outpost_hallway
/area/rnd/outpost/xenobiology/outpost_main
/area/rnd/outpost/xenobiology/outpost_north_airlock
/area/rnd/outpost/xenobiology/outpost_office
/area/rnd/outpost/xenobiology/outpost_slimepens
/area/rnd/outpost/xenobiology/outpost_south_airlock
/area/rnd/outpost/xenobiology/outpost_stairs
/area/rnd/outpost/xenobiology/outpost_storage
/area/rnd/rdoffice
/area/rnd/research
/area/rnd/research_storage
/area/rnd/research/researchdivision
/area/rnd/research/testingrange
/area/rnd/robotics
/area/rnd/robotics/mechbay
/area/rnd/robotics/resleeving
/area/rnd/robotics/surgeryroom1
/area/rnd/robotics/surgeryroom2
/area/rnd/staircase/secondfloor
/area/rnd/staircase/thirdfloor
/area/rnd/tankstorage
/area/rnd/testingroom
/area/rnd/workshop
/area/rnd/xenoarch_storage
/area/rnd/xenobiology/xenoflora
/area/rnd/xenobiology/xenoflora_storage
/area/security/breakroom
/area/security/brig
/area/security/brig/bathroom
/area/security/brig/visitation
/area/security/checkpoint
/area/security/eva
/area/security/evidence_storage
/area/security/hallway
/area/security/hallwayaux
/area/security/interrogation
/area/security/lobby
/area/security/nuke_storage
/area/security/observation
/area/security/recstorage
/area/security/riot_control
/area/security/security_bathroom
/area/security/security_cell_hallway
/area/security/security_equiptment_storage
/area/security/security_lockerroom
/area/security/security_processing
/area/server
/area/shuttle/belter
/area/shuttle/excursion/cargo
/area/shuttle/excursion/cockpit
/area/shuttle/excursion/general
/area/shuttle/large_escape_pod1
/area/shuttle/medivac/cockpit
/area/shuttle/medivac/engines
/area/shuttle/medivac/general
/area/shuttle/mining_outpost/shuttle
/area/shuttle/securiship/cockpit
/area/shuttle/securiship/engines
/area/shuttle/securiship/general
/area/shuttle/tether
/area/shuttle/tether/crash2
/area/shuttle/tourbus/cockpit
/area/shuttle/tourbus/general
/area/storage/art
/area/storage/emergency_storage/emergency3
/area/storage/emergency_storage/emergency4
/area/storage/primary
/area/storage/surface_eva
/area/storage/surface_eva/external
	area_flags = AREA_FLAG_EXTERNAL | AREA_FLAG_IS_NOT_PERSISTENT | AREA_FLAG_IS_BACKGROUND | AREA_FLAG_HIDE_FROM_HOLOMAP
	is_outside = TRUE
/area/storage/tech
/area/storage/tools
/area/tcomfoyer
/area/tcommsat/chamber
/area/tcommsat/computer
/area/tcommsat/entrance
/area/tcomsat
/area/teleporter
/area/teleporter/departing
/area/tether/elevator
	requires_power = FALSE
/area/tether/exploration/crew
/area/tether/exploration/equipment
/area/tether/exploration/hallway
/area/tether/exploration/pathfinder_office
/area/tether/exploration/showers
/area/tether/exploration/staircase
/area/tether/midpoint
/area/tether/station/burial
/area/tether/station/dock_one
/area/tether/station/dock_two
/area/tether/station/public_meeting_room
/area/tether/station/stairs_one
/area/tether/station/stairs_three
/area/tether/station/stairs_two
/area/tether/station/visitorhallway
/area/tether/station/visitorhallway/laundry
/area/tether/station/visitorhallway/lounge
/area/tether/station/visitorhallway/office
/area/tether/surfacebase/bar_backroom
/area/tether/surfacebase/barbackmaintenance
/area/tether/surfacebase/botanystorage
/area/tether/surfacebase/cafeteria
/area/tether/surfacebase/cargostore/office
/area/tether/surfacebase/cargostore/warehouse
/area/tether/surfacebase/east_stairs_two
/area/tether/surfacebase/emergency_storage/atmos
/area/tether/surfacebase/emergency_storage/atrium
/area/tether/surfacebase/emergency_storage/rnd
/area/tether/surfacebase/entertainment
/area/tether/surfacebase/entertainment/backstage
/area/tether/surfacebase/entertainment/stage
/area/tether/surfacebase/fish_farm
/area/tether/surfacebase/library/study
/area/tether/surfacebase/lowernortheva
/area/tether/surfacebase/lowernortheva/external
	area_flags = AREA_FLAG_EXTERNAL | AREA_FLAG_IS_NOT_PERSISTENT | AREA_FLAG_IS_BACKGROUND | AREA_FLAG_HIDE_FROM_HOLOMAP
	is_outside = TRUE
/area/tether/surfacebase/lowernorthhall
/area/tether/surfacebase/medical/admin
/area/tether/surfacebase/medical/bathroom
/area/tether/surfacebase/medical/breakroom
/area/tether/surfacebase/medical/centralhall
/area/tether/surfacebase/medical/centralstairwell
/area/tether/surfacebase/medical/chemistry
/area/tether/surfacebase/medical/cmo
/area/tether/surfacebase/medical/examroom
/area/tether/surfacebase/medical/first_aid_west
/area/tether/surfacebase/medical/lobby
/area/tether/surfacebase/medical/lowerhall
/area/tether/surfacebase/medical/mentalhealth
/area/tether/surfacebase/medical/morgue
/area/tether/surfacebase/medical/paramed
/area/tether/surfacebase/medical/patient_a
/area/tether/surfacebase/medical/patient_b
/area/tether/surfacebase/medical/patient_c
/area/tether/surfacebase/medical/recoveryward
/area/tether/surfacebase/medical/resleeving
/area/tether/surfacebase/medical/storage
/area/tether/surfacebase/medical/surgery1
/area/tether/surfacebase/medical/surgery2
/area/tether/surfacebase/medical/triage
/area/tether/surfacebase/medical/uppernorthstairwell
/area/tether/surfacebase/medical/uppersouthstairwell
/area/tether/surfacebase/north_staires_two
/area/tether/surfacebase/north_stairs_one
/area/tether/surfacebase/north_stairs_three
/area/tether/surfacebase/outside
	is_outside = TRUE
/area/tether/surfacebase/outside/outside1
/area/tether/surfacebase/outside/outside2
/area/tether/surfacebase/outside/outside3
/area/tether/surfacebase/public_garden
/area/tether/surfacebase/public_garden_one
/area/tether/surfacebase/public_garden_three
/area/tether/surfacebase/public_garden_two
/area/tether/surfacebase/reading_room
/area/tether/surfacebase/security/armory
/area/tether/surfacebase/security/breakroom
/area/tether/surfacebase/security/briefingroom
/area/tether/surfacebase/security/brig
/area/tether/surfacebase/security/brig/bathroom
/area/tether/surfacebase/security/brig/storage
/area/tether/surfacebase/security/detective
/area/tether/surfacebase/security/detective/officea
/area/tether/surfacebase/security/detective/officeb
/area/tether/surfacebase/security/evastorage
/area/tether/surfacebase/security/evidence
/area/tether/surfacebase/security/gasstorage
/area/tether/surfacebase/security/hos
/area/tether/surfacebase/security/iaa
/area/tether/surfacebase/security/iaa/officea
/area/tether/surfacebase/security/iaa/officeb
/area/tether/surfacebase/security/iaa/officecommon
/area/tether/surfacebase/security/interrogation
/area/tether/surfacebase/security/lobby
/area/tether/surfacebase/security/lowerhall
/area/tether/surfacebase/security/middlehall
/area/tether/surfacebase/security/outfitting
/area/tether/surfacebase/security/outfitting/storage
/area/tether/surfacebase/security/processing
/area/tether/surfacebase/security/upperhall
/area/tether/surfacebase/security/warden
/area/tether/surfacebase/security/weaponsrange
/area/tether/surfacebase/servicebackroom
/area/tether/surfacebase/shuttle_pad
/area/tether/surfacebase/southhall
/area/tether/surfacebase/surface_one_hall
/area/tether/surfacebase/surface_three_hall
/area/tether/surfacebase/surface_two_hall
/area/tether/surfacebase/topairlock
/area/tether/surfacebase/tram
/area/vacant/vacant_bar
/area/vacant/vacant_bar_upper
/area/vacant/vacant_restaurant_lower
/area/vacant/vacant_restaurant_upper
/area/vacant/vacant_shop
/area/vacant/vacant_site
/area/vacant/vacant_site/east
/area/maintenance/substation/outpost
/area/outpost/mining_main/break_room
/area/outpost/mining_main/dorms
/area/outpost/mining_main/drill_equipment
/area/outpost/mining_main/maintenance
/area/outpost/mining_main/passage
/area/outpost/mining_main/secondary_gear_storage
/area/rnd/outpost/airlock
/area/rnd/outpost/anomaly_lab
/area/rnd/outpost/anomaly_lab/airlock
/area/rnd/outpost/anomaly_lab/analysis
/area/rnd/outpost/anomaly_lab/storage
/area/rnd/outpost/anomaly_lab/testing
/area/rnd/outpost/atmos
/area/rnd/outpost/breakroom
/area/rnd/outpost/chamber
/area/rnd/outpost/eva
/area/rnd/outpost/heating
/area/rnd/outpost/mixing
/area/rnd/outpost/storage
/area/rnd/outpost/testing
/area/rnd/outpost/xenoarch_storage
/area/shuttle/tether/crash1
/area/tether/outpost/solars_outside
/area/tether/outpost/solars_shed