/obj/item/clothing/accessory/armor/armguards
/obj/item/clothing/accessory/armor/legguards
/obj/item/clothing/accessory/collar/pink
/obj/item/clothing/accessory/collar/shock
/obj/item/clothing/accessory/permit/gun/bar
/obj/item/clothing/accessory/permit/gun/paramedic
/obj/item/clothing/accessory/permit/gun/planetside
/obj/item/clothing/accessory/poncho/roles/medical
/obj/item/clothing/accessory/scarf/stripedred
/obj/item/clothing/glasses/gglasses
/obj/item/clothing/glasses/goggles
/obj/item/clothing/glasses/omnihud/all
/obj/item/clothing/glasses/omnihud/rnd
/obj/item/clothing/glasses/sunglasses/sechud/tactical
/obj/item/clothing/head/beret/centcom
/obj/item/clothing/head/beret/nanotrasen
/obj/item/clothing/head/helmet/combat
/obj/item/clothing/head/helmet/ert/command
/obj/item/clothing/head/helmet/space/deathsquad
/obj/item/clothing/head/helmet/space/skrell/black
/obj/item/clothing/head/helmet/space/skrell/white
/obj/item/clothing/head/helmet/space/void/captain
/obj/item/clothing/head/helmet/space/void/exploration
/obj/item/clothing/head/helmet/space/void/headofsecurity
/obj/item/clothing/head/helmet/space/void/medical/bio
/obj/item/clothing/head/helmet/space/void/medical/emt
/obj/item/clothing/head/pilot
/obj/item/clothing/mask/gas/wwii
/obj/item/clothing/mask/smokable/cigarette/joint
/obj/item/clothing/shoes/magboots/adv
/obj/item/clothing/shoes/mime
/obj/item/clothing/shoes/winterboots/medical
/obj/item/clothing/suit/armor/combat
/obj/item/clothing/suit/armor/riot/alt
/obj/item/clothing/suit/armor/swat
/obj/item/clothing/suit/armor/tactical
/obj/item/clothing/suit/armor/vest/ert/command
/obj/item/clothing/suit/armor/vest/wolftaur
/obj/item/clothing/suit/fire/firefighter
/obj/item/clothing/suit/space/skrell/black
/obj/item/clothing/suit/space/skrell/white
/obj/item/clothing/suit/space/void/captain
/obj/item/clothing/suit/space/void/exploration
/obj/item/clothing/suit/space/void/headofsecurity
/obj/item/clothing/suit/space/void/medical/bio
/obj/item/clothing/suit/space/void/medical/emt
/obj/item/clothing/under/bathrobe
/obj/item/clothing/under/batter
/obj/item/clothing/under/fluff/latexmaid