/obj/structure/symbol/da
/obj/structure/symbol/em
/obj/structure/symbol/es
/obj/structure/symbol/gu
/obj/structure/symbol/lo
/obj/structure/symbol/pr
/obj/structure/symbol/sa

/obj/effect/floor_decal/derelict/d1
/obj/effect/floor_decal/derelict/d10
/obj/effect/floor_decal/derelict/d11
/obj/effect/floor_decal/derelict/d12
/obj/effect/floor_decal/derelict/d13
/obj/effect/floor_decal/derelict/d14
/obj/effect/floor_decal/derelict/d15
/obj/effect/floor_decal/derelict/d16
/obj/effect/floor_decal/derelict/d2
/obj/effect/floor_decal/derelict/d3
/obj/effect/floor_decal/derelict/d4
/obj/effect/floor_decal/derelict/d5
/obj/effect/floor_decal/derelict/d6
/obj/effect/floor_decal/derelict/d7
/obj/effect/floor_decal/derelict/d8
/obj/effect/floor_decal/derelict/d9
/obj/effect/floor_decal/rust/mono_rusted1
/obj/effect/floor_decal/rust/mono_rusted3
/obj/effect/floor_decal/rust/part_rusted3
/obj/effect/floor_decal/rust/part_rusted3
/obj/effect/floor_decal/borderfloor/shifted
/obj/effect/floor_decal/corner_oldtile/green
/obj/effect/floor_decal/corner_oldtile/green/full
/obj/effect/floor_decal/corner/blue/border/shifted
/obj/effect/floor_decal/corner/grey/bordercorner2
/obj/effect/floor_decal/corner/lightgrey/border/shifted
/obj/effect/floor_decal/corner/lightorange
/obj/effect/floor_decal/corner/lightorange/border
/obj/effect/floor_decal/corner/lightorange/border/shifted
/obj/effect/floor_decal/corner/lightorange/bordercorner
/obj/effect/floor_decal/corner/lightorange/bordercorner2
/obj/effect/floor_decal/corner/purple/border/shifted
/obj/effect/floor_decal/corner/red/border/shifted
/obj/effect/floor_decal/corner/white/border/shifted