/obj/item/ammo_casing/a12g/beanbag
/obj/item/ammo_casing/nsfw_batt
/obj/item/ammo_casing/nsfw_batt/net
/obj/item/ammo_casing/nsfw_batt/stun
/obj/item/ammo_magazine/clip/c762/practice
/obj/item/ammo_magazine/m44
/obj/item/ammo_magazine/m45/practice
/obj/item/ammo_magazine/m45/rubber
/obj/item/ammo_magazine/m545
/obj/item/ammo_magazine/m545/ap
/obj/item/ammo_magazine/m545saw
/obj/item/ammo_magazine/m545saw/ap
/obj/item/ammo_magazine/m762
/obj/item/ammo_magazine/m762/ap
/obj/item/ammo_magazine/m95
/obj/item/ammo_magazine/m9mm/large/preban
/obj/item/ammo_magazine/m9mml
/obj/item/ammo_magazine/m9mml/ap
/obj/item/ammo_magazine/m9mmp90
/obj/item/ammo_magazine/m9mmR/saber
/obj/item/ammo_magazine/m9mmt/practice
/obj/item/ammo_magazine/m9mmt/rubber
/obj/item/ammo_magazine/nsfw_mag
/obj/item/ammo_magazine/s44
/obj/item/ammo_magazine/s45
/obj/item/gun/energy/frontier/locked
/obj/item/gun/energy/frontier/locked/holdout
/obj/item/gun/energy/gun/burst
/obj/item/gun/energy/gun/martin
/obj/item/gun/energy/ionrifle/pistol
/obj/item/gun/energy/netgun
/obj/item/gun/energy/phasegun/pistol
/obj/item/gun/energy/sizegun
/obj/item/gun/energy/stunrevolver
/obj/item/gun/energy/taser/xeno
/obj/item/gun/projectile/automatic/advanced_smg
/obj/item/gun/projectile/automatic/battlerifle
/obj/item/gun/projectile/automatic/bullpup
/obj/item/gun/projectile/automatic/l6_saw
/obj/item/gun/projectile/automatic/p90
/obj/item/gun/projectile/automatic/pdw
/obj/item/gun/projectile/automatic/sts35
/obj/item/gun/projectile/automatic/wt550
/obj/item/gun/projectile/automatic/wt550/lethal
/obj/item/gun/projectile/automatic/z8
/obj/item/gun/projectile/deagle
/obj/item/gun/projectile/heavysniper
/obj/item/gun/projectile/nsfw
/obj/item/gun/projectile/p92x
/obj/item/gun/projectile/revolver/consul
/obj/item/gun/projectile/revolver/detective45
/obj/item/gun/projectile/shotgun/pump/combat
/obj/item/gun/projectile/shotgun/pump/rifle/practice
/obj/item/gun/projectile/shotgun/pump/USDF
/obj/item/gunbox
/obj/item/knife/tacknife/survival
/obj/item/twohanded/fireaxe/foam
/obj/item/twohanded/spear/foam